# Generated by Django 4.2.4 on 2024-02-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='affiliation',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='talent',
            name='birthday',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='talent',
            name='debut_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='talent',
            name='fan_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='funclub_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='name_ruby',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='twitch_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='x_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='youtube_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
