# Generated by Django 4.2.4 on 2024-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='debut_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='talent',
            name='fanclub_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='talent',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='talent',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='talent',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
