# Generated by Django 4.2.4 on 2024-02-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talents', '0002_talent_debut_at_talent_fanclub_url_talent_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='affiliation',
            field=models.CharField(default='', max_length=20),
        ),
    ]
